/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            /** @enum {string} */
                            db: "up" | "down";
                        };
                    };
                };
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user and credit balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                clerkId: string;
                            };
                            credits: {
                                balanceMicro: string;
                                formatted: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chats (unpinned by default), pinned chats with pinned=true, or search titles with q */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    q?: string;
                    pinned?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: string;
                                title: string;
                                pinned: boolean;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Create a chat */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            title: string;
                            pinned: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                401: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One chat and its active run */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chat: {
                                id: string;
                                title: string;
                                pinned: boolean;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            activeRun: {
                                runId: string;
                                /** @enum {string} */
                                status: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled";
                                waitpoint: {
                                    id: string;
                                    /** @enum {string} */
                                    kind: "options" | "plan" | "credit" | "media";
                                    request: {
                                        /** @constant */
                                        kind: "options";
                                        question: string;
                                        options: string[];
                                    } | {
                                        /** @constant */
                                        kind: "media";
                                        question: string;
                                        files: {
                                            name: string;
                                            /** Format: uri */
                                            url: string;
                                            /** @enum {string} */
                                            kind: "image" | "video" | "audio";
                                        }[];
                                    } | {
                                        /** @constant */
                                        kind: "plan";
                                        summary: string;
                                        steps: {
                                            text: string;
                                            tool?: string;
                                            args?: string;
                                        }[];
                                        estimateMicro: number;
                                    } | {
                                        /** @constant */
                                        kind: "credit";
                                        tools: {
                                            name: string;
                                            estimateMicro: number;
                                        }[];
                                        stepMicro: number;
                                        totalMicro: number;
                                    };
                                    /** Format: date-time */
                                    expiresAt: string;
                                } | null;
                            } | null;
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a chat (refused while a reply is running) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /** Pin, unpin or rename a chat */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        pinned?: boolean;
                        title?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            title: string;
                            pinned: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Message history, newest first */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: string;
                                /** @enum {string} */
                                role: "user" | "assistant" | "system" | "tool";
                                /** @enum {string} */
                                status: "streaming" | "success" | "failed" | "cancelled";
                                runId: string | null;
                                checkpointStep: number;
                                content: ({
                                    /** @constant */
                                    type: "text";
                                    text: string;
                                } | {
                                    /** @constant */
                                    type: "thinking";
                                    text: string;
                                    durationMs?: number;
                                } | {
                                    /** @constant */
                                    type: "tool_use";
                                    toolCallId: string;
                                    name: string;
                                    input: unknown;
                                } | {
                                    /** @constant */
                                    type: "tool_result";
                                    toolCallId: string;
                                    /** @enum {string} */
                                    status: "completed" | "failed" | "cancelled";
                                    output?: unknown;
                                    error?: {
                                        code: string;
                                        message: string;
                                        retryable: boolean;
                                    };
                                    creditsMicro?: number;
                                    durationMs?: number;
                                } | {
                                    /** @constant */
                                    type: "asset";
                                    /** @enum {string} */
                                    kind: "image" | "video" | "audio";
                                    /** Format: uri */
                                    url: string;
                                    toolCallId: string;
                                    ref?: string;
                                    durationSec?: number;
                                } | {
                                    /** @constant */
                                    type: "attachment";
                                    attachmentId: string;
                                    ref?: string;
                                    /** @enum {string} */
                                    kind: "image" | "video" | "audio";
                                    /** Format: uri */
                                    url: string;
                                    name: string;
                                    mime: string;
                                    width: number | null;
                                    height: number | null;
                                    durationSec?: number | null;
                                } | {
                                    /** @constant */
                                    type: "error";
                                    error: {
                                        code: string;
                                        message: string;
                                        retryable: boolean;
                                    };
                                } | {
                                    /** @constant */
                                    type: "usage";
                                    creditsMicro: number;
                                    promptTokens: number;
                                    completionTokens: number;
                                    models: string[];
                                })[];
                                error: {
                                    code: string;
                                    message: string;
                                    retryable: boolean;
                                } | null;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Send a message and start the agent turn */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        clientMessageId: string;
                        text: string;
                        /** @default [] */
                        attachmentIds?: string[];
                        /** @default false */
                        planMode?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chatId: string;
                            messageId: string;
                            runId: string;
                            realtime: {
                                triggerRunId: string;
                                publicAccessToken: string;
                                /** Format: date-time */
                                expiresAt: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Error"];
                402: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
                429: components["responses"]["Error"];
                503: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signed Transloadit Assembly params for one upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            params: string;
                            signature: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
                401: components["responses"]["Error"];
                422: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a finished Assembly and save its files as attachments */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        assemblyId: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            attachments: {
                                id: string;
                                /** @enum {string} */
                                kind: "image" | "video" | "audio";
                                name: string;
                                mime: string;
                                sizeBytes: number;
                                width: number | null;
                                height: number | null;
                                durationSec: number | null;
                                /** Format: uri */
                                url: string;
                                persistent: boolean;
                            }[];
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run status, tool calls and the assistant message */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            run: {
                                id: string;
                                chatId: string;
                                /** @enum {string} */
                                status: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled";
                                steps: number;
                                routedModels: string[];
                                error: {
                                    code: string;
                                    message: string;
                                    retryable: boolean;
                                } | null;
                                /** Format: date-time */
                                createdAt: string;
                                finishedAt: string | null;
                            };
                            tools: {
                                toolCallId: string;
                                seq: number;
                                name: string;
                                /** @enum {string} */
                                status: "pending" | "dispatching" | "running" | "completed" | "failed" | "cancelled";
                                input: unknown;
                                output: unknown | null;
                                durationMs: number | null;
                                credits: string;
                                error: {
                                    code: string;
                                    message: string;
                                    retryable: boolean;
                                } | null;
                            }[];
                            assistantMessage: {
                                id: string;
                                /** @enum {string} */
                                role: "user" | "assistant" | "system" | "tool";
                                /** @enum {string} */
                                status: "streaming" | "success" | "failed" | "cancelled";
                                runId: string | null;
                                checkpointStep: number;
                                content: ({
                                    /** @constant */
                                    type: "text";
                                    text: string;
                                } | {
                                    /** @constant */
                                    type: "thinking";
                                    text: string;
                                    durationMs?: number;
                                } | {
                                    /** @constant */
                                    type: "tool_use";
                                    toolCallId: string;
                                    name: string;
                                    input: unknown;
                                } | {
                                    /** @constant */
                                    type: "tool_result";
                                    toolCallId: string;
                                    /** @enum {string} */
                                    status: "completed" | "failed" | "cancelled";
                                    output?: unknown;
                                    error?: {
                                        code: string;
                                        message: string;
                                        retryable: boolean;
                                    };
                                    creditsMicro?: number;
                                    durationMs?: number;
                                } | {
                                    /** @constant */
                                    type: "asset";
                                    /** @enum {string} */
                                    kind: "image" | "video" | "audio";
                                    /** Format: uri */
                                    url: string;
                                    toolCallId: string;
                                    ref?: string;
                                    durationSec?: number;
                                } | {
                                    /** @constant */
                                    type: "attachment";
                                    attachmentId: string;
                                    ref?: string;
                                    /** @enum {string} */
                                    kind: "image" | "video" | "audio";
                                    /** Format: uri */
                                    url: string;
                                    name: string;
                                    mime: string;
                                    width: number | null;
                                    height: number | null;
                                    durationSec?: number | null;
                                } | {
                                    /** @constant */
                                    type: "error";
                                    error: {
                                        code: string;
                                        message: string;
                                        retryable: boolean;
                                    };
                                } | {
                                    /** @constant */
                                    type: "usage";
                                    creditsMicro: number;
                                    promptTokens: number;
                                    completionTokens: number;
                                    models: string[];
                                })[];
                                error: {
                                    code: string;
                                    message: string;
                                    retryable: boolean;
                                } | null;
                                /** Format: date-time */
                                createdAt: string;
                            } | null;
                            waitpoint: {
                                id: string;
                                /** @enum {string} */
                                kind: "options" | "plan" | "credit" | "media";
                                request: {
                                    /** @constant */
                                    kind: "options";
                                    question: string;
                                    options: string[];
                                } | {
                                    /** @constant */
                                    kind: "media";
                                    question: string;
                                    files: {
                                        name: string;
                                        /** Format: uri */
                                        url: string;
                                        /** @enum {string} */
                                        kind: "image" | "video" | "audio";
                                    }[];
                                } | {
                                    /** @constant */
                                    kind: "plan";
                                    summary: string;
                                    steps: {
                                        text: string;
                                        tool?: string;
                                        args?: string;
                                    }[];
                                    estimateMicro: number;
                                } | {
                                    /** @constant */
                                    kind: "credit";
                                    tools: {
                                        name: string;
                                        estimateMicro: number;
                                    }[];
                                    stepMicro: number;
                                    totalMicro: number;
                                };
                                /** Format: date-time */
                                expiresAt: string;
                            } | null;
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint a realtime read token for one run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            triggerRunId: string;
                            publicAccessToken: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a failed or stopped reply again for the same message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chatId: string;
                            messageId: string;
                            runId: string;
                            realtime: {
                                triggerRunId: string;
                                publicAccessToken: string;
                                /** Format: date-time */
                                expiresAt: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Error"];
                402: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
                429: components["responses"]["Error"];
                503: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop an active run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            runId: string;
                            status: ("queued" | "running" | "waiting" | "completed" | "failed" | "cancelled") | "stopping";
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitpoints/{waitpointId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a question the agent is waiting on (option, file, plan or cost approval) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    waitpointId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        choice: string;
                    } | {
                        approve: boolean;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            status: "pending" | "answered" | "expired" | "cancelled";
                        };
                    };
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
                503: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RunMeta: {
            /** @enum {string} */
            status: "thinking" | "working" | "waiting" | "complete" | "failed" | "cancelled" | "stopping";
            step: number;
            label?: string;
            error?: {
                code: string;
                message: string;
                retryable: boolean;
            };
            waitpoint?: {
                id: string;
                /** @enum {string} */
                kind: "options" | "plan" | "credit" | "media";
                request: {
                    /** @constant */
                    kind: "options";
                    question: string;
                    options: string[];
                } | {
                    /** @constant */
                    kind: "media";
                    question: string;
                    files: {
                        name: string;
                        /** Format: uri */
                        url: string;
                        /** @enum {string} */
                        kind: "image" | "video" | "audio";
                    }[];
                } | {
                    /** @constant */
                    kind: "plan";
                    summary: string;
                    steps: {
                        text: string;
                        tool?: string;
                        args?: string;
                    }[];
                    estimateMicro: number;
                } | {
                    /** @constant */
                    kind: "credit";
                    tools: {
                        name: string;
                        estimateMicro: number;
                    }[];
                    stepMicro: number;
                    totalMicro: number;
                };
                /** Format: date-time */
                expiresAt: string;
            };
            tools: {
                [key: string]: {
                    name: string;
                    /** @enum {string} */
                    status: "pending" | "dispatching" | "running" | "completed" | "failed" | "cancelled";
                    seq: number;
                    durationMs?: number;
                    credits?: string;
                    assetUrl?: string;
                    /** @enum {string} */
                    assetKind?: "image" | "video" | "audio";
                    error?: {
                        code: string;
                        message: string;
                        retryable: boolean;
                    };
                };
            };
        };
        StreamPart: {
            /** @enum {string} */
            t: "text" | "thinking";
            step: number;
            d: string;
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @enum {string} */
                        code: "unauthenticated" | "insufficient_credits" | "not_found" | "run_active" | "run_not_dispatched" | "run_finished" | "waitpoint_closed" | "run_not_retryable" | "validation_failed" | "rate_limited" | "upload_not_ready" | "upload_rejected" | "upload_quota" | "dispatch_failed" | "internal";
                        message: string;
                        traceId: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
